### ISSUE TITLE
support sqlite and postgres

### ISSUE THREAD

**Issue by ahmedRSA** [ookamiiixd/baileys-store#2]
not everyone is fan mysql
i think adding support of postgres and sqlite will help many

**Comment by ookamiiixd** [comment]
That's why i choose Prisma, Prisma supports many popular DBMS

Doesn't this line sounds obvious?
> Additionaly, you may want to update your provider in the schema.prisma file if you're not using MySQL database.

Or maybe i should update it with something more  obvious?
